version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
    networks:
      - dev-network

  migration:
    depends_on:
      db:
          condition: service_healthy
    build:
      context: .
      dockerfile: ./deployment/migration.Dockerfile
    links:
      - db
    networks:
      - dev-network

  api:
    depends_on:
      - migration
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./deployment/api.Dockerfile
    links:
      - db
    networks:
      - dev-network

networks:
  dev-network: